// src/pages/FeeStructure.jsx

import React from 'react';
import { Link } from 'react-router-dom';
import Layout from '../components/Layout';

const FeeStructure = () => {
  return (
    <Layout>
      <div className="faq-container"> {/* We can reuse the FAQ container style for a consistent look */}
        <h1>Platform Tiers & Fees</h1>
        <p className="faq-intro">
          Our system is designed to reward long-term participation. Users level up their Account Tier by earning XP, which provides benefits like reduced deposit fees.
        </p>

        {/* --- Account Tiers Section --- */}
        <div className="info-section">
          <h2>Account Tiers</h2>
          <p>Your Account Tier is determined by your total XP. Higher tiers unlock better fee rates.</p>
          <table className="info-table">
            <thead>
              <tr>
                <th>Tier</th>
                <th>XP Required</th>
                <th>Deposit Fee Discount</th>
              </tr>
            </thead>
            <tbody>
              <tr><td>Tier 1</td><td>0 - 749 XP</td><td>Base Fee (20%)</td></tr>
              <tr><td>Tier 2</td><td>750 - 1,499 XP</td><td>-2% (18% Fee)</td></tr>
              <tr><td>Tier 3</td><td>1,500 - 2,999 XP</td><td>-4% (16% Fee)</td></tr>
              <tr><td>Tier 4</td><td>3,000+ XP</td><td>-6% (14% Fee)</td></tr>
              {/* <tr><td>Tier 5</td><td>Coming Soon</td><td>-8% (12% Fee)</td></tr> */}
            </tbody>
          </table>
        </div>

        {/* --- How to Earn XP Section --- */}
        <div className="info-section">
          <h2>How to Earn XP</h2>
          <p>XP is earned through value-additive actions within the ecosystem. See your rank on the <Link to="/xpleaderboard">XP Leaderboard</Link>.</p>
          <ul className="info-list">
            <li>
              <strong>Capital Allocation:</strong> Earn 1 XP for every $10 of capital allocated to a vault.
            </li>
            <li>
              <strong>Time-Staked Bonus:</strong> Earn daily XP based on the amount of capital you have locked in a vault. The current rate is approximately (Capital / 300) XP per day.
            </li>
            <li>
              <strong>Successful Referrals:</strong> When a user you refer makes their first allocation, you earn bonus XP.
            </li>
          </ul>
        </div>
        
        {/* --- Vault Fees Section --- */}
        <div className="info-section">
          <h2>Vault Fees Explained</h2>
          <p>There are two types of fees on the platform:</p>
          <ul className="info-list">
            <li>
              <strong>Deposit Fee (10-20%):</strong> This is a one-time fee on new capital allocations. 80% of this fee is credited back to you as Bonus Points, and 20% is used for operations. Your Account Tier provides a discount on this fee.
            </li>
            <li>
              <strong>Performance Fee (20-40%):</strong> This fee is only charged on the profits generated by the trading strategies. It is not charged on your principal capital. Each vault has its own performance fee rate.
            </li>
          </ul>
        </div>

      </div>
    </Layout>
  );
};

export default FeeStructure;